# Generated by Django 3.0.6 on 2020-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200529_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user_pics/default.png', upload_to='user_pics', verbose_name='profile image'),
        ),
    ]
