# Generated by Django 3.0.6 on 2020-05-25 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='event',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='user',
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.SurveyQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
